# Pre-commit hooks for code quality and consistency
# Install with: pre-commit install
# Run manually with: pre-commit run --all-files

repos:
  # Ruff - Fast Python linter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.2
    hooks:
      - id: ruff
        args: [--fix]
        name: ruff (linting)

  # Black - Python code formatter
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        name: black (formatting)
        language_version: python3.12

  # mypy - Static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        name: mypy (type checking)
        verbose: true
        additional_dependencies:
          - pydantic>=2.9.0
          - types-PyYAML
          - types-click
          - anthropic
          - structlog
        args: [--config-file=pyproject.toml, --ignore-missing-imports]
        exclude: ^tests/

  # Bandit - Security linter
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        name: bandit (security)
        args: [-r, src/agentic, -c, pyproject.toml]
        pass_filenames: false
        exclude: ^tests/

  # Flake8 - Python style guide enforcement
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        name: flake8 (style guide)
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-import-order
          - flake8-docstrings
          - pydocstyle
        args: [--config=pyproject.toml, --max-line-length=100, --]
        exclude: ^tests/

  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        name: trim trailing whitespace
      - id: end-of-file-fixer
        name: fix end of files
      - id: check-yaml
        name: check yaml syntax
        exclude: ^\.github/workflows/
      - id: check-added-large-files
        name: check for large files
        args: [--maxkb=1000]
      - id: check-merge-conflict
        name: check for merge conflicts
      - id: detect-private-key
        name: detect private keys
      - id: check-toml
        name: check toml syntax
      - id: check-json
        name: check json syntax
      - id: mixed-line-ending
        name: check line endings
        args: [--fix=lf]
