apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: llm-trader-prod
  labels:
    app: llm-crypto-trader
    component: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        cluster: 'llm-trader-prod'
        environment: 'production'

    # Alerting configuration
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - alertmanager:9093

    # Rule files
    rule_files:
      - '/etc/prometheus/rules/*.yml'

    # Scrape configurations
    scrape_configs:
      # Scrape Prometheus itself
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      # Scrape LLM Trader application metrics
      - job_name: 'llm-trader-app'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - llm-trader-prod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name

      # Scrape Kubernetes nodes
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)

      # Scrape Kubernetes services
      - job_name: 'kubernetes-services'
        kubernetes_sd_configs:
          - role: service
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_port]
            action: replace
            regex: (.+)
            target_label: __param_target__
          - source_labels: [__param_target__]
            action: replace
            target_label: instance
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_service_name]
            action: replace
            target_label: kubernetes_name

      # Scrape PostgreSQL exporter
      - job_name: 'postgres'
        static_configs:
          - targets: ['postgres-exporter:9187']
        metrics_path: '/metrics'

      # Scrape Redis exporter
      - job_name: 'redis'
        static_configs:
          - targets: ['redis-exporter:9121']
        metrics_path: '/metrics'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: llm-trader-prod
  labels:
    app: llm-crypto-trader
    component: monitoring
data:
  trading-alerts.yml: |
    groups:
      - name: trading_alerts
        interval: 30s
        rules:
          # High-level trading alerts
          - alert: TradingSystemDown
            expr: up{job="llm-trader-app"} == 0
            for: 2m
            labels:
              severity: critical
              component: trading
            annotations:
              summary: "Trading system is down"
              description: "{{ $labels.instance }} has been down for more than 2 minutes."

          - alert: NoTradingActivity
            expr: rate(trading_decisions_total[10m]) == 0
            for: 15m
            labels:
              severity: warning
              component: trading
            annotations:
              summary: "No trading decisions made"
              description: "No trading decisions have been made in the last 15 minutes."

          - alert: HighErrorRate
            expr: rate(trading_errors_total[5m]) > 0.1
            for: 5m
            labels:
              severity: critical
              component: trading
            annotations:
              summary: "High error rate in trading system"
              description: "Error rate is {{ $value }} errors per second."

          # Position and risk alerts
          - alert: PositionDriftDetected
            expr: position_drift_percentage > 1
            for: 5m
            labels:
              severity: warning
              component: reconciliation
            annotations:
              summary: "Position drift detected"
              description: "Position drift of {{ $value }}% detected for {{ $labels.symbol }}."

          - alert: RiskLimitExceeded
            expr: portfolio_exposure_ratio > 0.85
            for: 1m
            labels:
              severity: critical
              component: risk
            annotations:
              summary: "Portfolio risk limit exceeded"
              description: "Portfolio exposure is at {{ $value }}% of limit."

          - alert: StopLossTriggered
            expr: increase(stop_loss_triggered_total[1m]) > 0
            labels:
              severity: warning
              component: risk
            annotations:
              summary: "Stop loss triggered"
              description: "Stop loss triggered for {{ $labels.symbol }}."

          # Performance alerts
          - alert: HighLatency
            expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
            for: 5m
            labels:
              severity: warning
              component: performance
            annotations:
              summary: "High API latency"
              description: "95th percentile latency is {{ $value }}s."

          - alert: LowCacheHitRate
            expr: cache_hit_rate < 0.3
            for: 10m
            labels:
              severity: warning
              component: performance
            annotations:
              summary: "Low cache hit rate"
              description: "Cache hit rate is {{ $value }}%."

          # Infrastructure alerts
          - alert: DatabaseConnectionFailure
            expr: database_connections_active == 0
            for: 1m
            labels:
              severity: critical
              component: database
            annotations:
              summary: "Database connection lost"
              description: "No active database connections available."

          - alert: RedisMemoryHigh
            expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.9
            for: 5m
            labels:
              severity: warning
              component: cache
            annotations:
              summary: "Redis memory usage high"
              description: "Redis memory usage is at {{ $value }}% of maximum."

          - alert: WebSocketDisconnected
            expr: websocket_connection_status == 0
            for: 2m
            labels:
              severity: critical
              component: websocket
            annotations:
              summary: "WebSocket disconnected"
              description: "WebSocket connection to exchange has been lost."

          # LLM and cost alerts
          - alert: HighLLMCost
            expr: rate(llm_api_cost_dollars[1h]) * 24 * 30 > 100
            for: 1h
            labels:
              severity: warning
              component: llm
            annotations:
              summary: "High LLM API costs"
              description: "Projected monthly LLM cost is ${{ $value }}."

          - alert: LLMResponseTimeout
            expr: rate(llm_request_timeouts_total[5m]) > 0.1
            for: 5m
            labels:
              severity: warning
              component: llm
            annotations:
              summary: "High LLM timeout rate"
              description: "LLM timeout rate is {{ $value }} per second."
