apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: llm-trader-prod
  labels:
    app: llm-crypto-trader
    component: redis
spec:
  serviceName: redis-service
  replicas: 1
  selector:
    matchLabels:
      app: llm-crypto-trader
      component: redis
  template:
    metadata:
      labels:
        app: llm-crypto-trader
        component: redis
    spec:
      securityContext:
        fsGroup: 999
      containers:
      - name: redis
        image: redis:7-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - name: redis
          containerPort: 6379
          protocol: TCP
        command:
        - redis-server
        - /usr/local/etc/redis/redis.conf
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: llm-trader-secrets
              key: REDIS_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          exec:
            command:
            - redis-cli
            - -a
            - $(REDIS_PASSWORD)
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - redis-cli
            - -a
            - $(REDIS_PASSWORD)
            - ping
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: redis-storage
          mountPath: /data
        - name: redis-config
          mountPath: /usr/local/etc/redis
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-pvc
      - name: redis-config
        configMap:
          name: redis-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: llm-trader-prod
  labels:
    app: llm-crypto-trader
    component: redis
data:
  redis.conf: |
    # Redis configuration for production

    # Network
    bind 0.0.0.0
    protected-mode yes
    port 6379
    tcp-backlog 511
    tcp-keepalive 300
    timeout 0

    # General
    daemonize no
    supervised no
    pidfile /var/run/redis_6379.pid
    loglevel notice
    logfile ""
    databases 16

    # Authentication
    requirepass ${REDIS_PASSWORD}

    # Persistence
    save 900 1
    save 300 10
    save 60 10000
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    dir /data

    # AOF persistence
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    no-appendfsync-on-rewrite no
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    aof-load-truncated yes
    aof-use-rdb-preamble yes

    # Memory management
    maxmemory 800mb
    maxmemory-policy allkeys-lru
    maxmemory-samples 5

    # Lazy freeing
    lazyfree-lazy-eviction no
    lazyfree-lazy-expire no
    lazyfree-lazy-server-del no
    replica-lazy-flush no

    # Threading
    io-threads 4
    io-threads-do-reads yes

    # Slow log
    slowlog-log-slower-than 10000
    slowlog-max-len 128

    # Client output buffer limits
    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit replica 256mb 64mb 60
    client-output-buffer-limit pubsub 32mb 8mb 60

    # Frequency settings
    hz 10

    # Active rehashing
    activerehashing yes

    # Modules
    # loadmodule /usr/lib/redis/modules/redisearch.so
    # loadmodule /usr/lib/redis/modules/redisjson.so
