apiVersion: v1
kind: Service
metadata:
  name: trading-engine-service
  namespace: trading-system
  labels:
    app: trading-engine
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  selector:
    app: trading-engine
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
  sessionAffinity: None
  externalTrafficPolicy: Cluster

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: trading-system
  labels:
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432
  sessionAffinity: None

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: trading-system
  labels:
    app: redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
  - name: redis
    protocol: TCP
    port: 6379
    targetPort: 6379
  sessionAffinity: None
